# Generated by Django 4.0 on 2021-12-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_Title', models.CharField(max_length=200)),
                ('vidl_Body', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Video',
            },
        ),
    ]
